name: Testing with Mysql & NodeJs

on: push

jobs:
  install_dependencies:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0

      - name: Cache node modules
        id: node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm install

      - run: tar -zcf node_modules.tar.gz node_modules

      - uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules.tar.gz
          retention-days: 1

  test:
    needs: [install_dependencies]

    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      PORT: 4000

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.17.0]
        ci_node_total: [8]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7]

    services:
      redis:
        image: redis:5-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
